### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [jakerutt/Dasmoto-s-Arts-and-Crafts#4]
Hey, this was a job well done. I really like how you got the design to look close to the specs that we laid out. Good job! However, you still need to fix habits such as keeping clean code and naming files and folders properly. You named a folder `index.html` and `css.css` and they normally aren't named like this. I think you did a good job with this and there were only minor fixes you needed to fix. Try to come back to this project after you've learned more about responsive design and media queries. You can try to apply the same concepts here and make a mobile-friendly page.

Summary: Satisfactory

**Comment by jakerutt** [comment]
Thank you for the review.  As a newbie to this, I am definitely struggling with the "clean code" rules and file path names.  Hopefully as I continue these classes these practices will become more clear.  I also struggled to get my mac to recognize the files unless I saved them a certain way, but that is probably my lack of understanding of the file path.
